name: React

on:
  push:
    branches: [ "main" ]
    paths: ["FrontEnd/**", "**/react.yml"]
  pull_request:
    branches: [ "main" ]
    paths: ["FrontEnd/**", "**/react.yml"]

env:
  NODE_VERSION: 22.12.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Yarn and Node.js Action
        uses: digi-fry/setup-yarn-node-action@v1
        with:
          node-version: ${{ env.NODE_VERSION }}          

      - name: Install dependencies using node class
        run: |
          # Initialize the project (if not already initialized) and install dependencies
          yarn install 
          yarn build
        working-directory: "./FrontEnd/"
    
      - name: Run tests using react-scripts with --ci flag
        run: |
          # Run tests non-interactively with react-scripts
          yarn test --watchAll=false
        working-directory: "./FrontEnd/build"
