name: React

on:
  push:
    branches: [ "main" ]
    paths: ["FrontEnd/**", "**/react.yml"]
  pull_request:
    branches: [ "main" ]
    paths: ["FrontEnd/**", "**/react.yml"]

env:
  NODE_VERSION: 22.12.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install Yarn
        run: |
          npm install yarn@1.22.22
        working-directory: "./FrontEnd/"

      - name: Install dependencies using yarn
        run: |
          # install dependencies
          yarn install 
          yarn build
        working-directory: "./FrontEnd/"
    
      - name: Run tests using react-scripts with --ci flag
        run: |
          # Run tests non-interactively with yarn
          yarn test --watchAll=false
        working-directory: "./FrontEnd/build"
