name: React

on:
  push:
    branches: [ "main" ]
    paths: ["FrontEnd/**", "**/react.yml"]
  pull_request:
    branches: [ "main" ]
    paths: ["FrontEnd/**", "**/react.yml"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '20.12'
          cache: 'yarn' # Enable Yarn caching for faster builds

      - name: Install dependencies using yarn
        run: |
          yarn install
          yarn build
        working-directory: "./FrontEnd/"
    
      - name: Run tests using react-scripts with --ci flag
        run: |
          yarn test --watchAll=false
        working-directory: "./FrontEnd/build"
